services:
  app:
    build:
      context: .
      dockerfile: Dockerfile # uses production Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    restart: unless-stopped
