name: local
variables:
  - name: baseUrl
    value: http://localhost:3000/api/v1
  - secret: true
    name: accessToken
  - secret: true
    name: sessionId
  - name: accessTokenExpiry
    value:
      type: number
      data: "1787112239000"
  - name: clientId
    value: ebc8690c-225b-4a3b-b0e3-e831d4633848
