name: local
variables:
  - name: baseUrl
    value: http://localhost:3000/api/v1
  - secret: true
    name: accessToken
  - secret: true
    name: sessionId
  - name: accessTokenExpiry
    value:
      type: number
      data: "1787062844000"
  - name: clientId
    value: e5129f8f-62ff-4bc2-8819-e82bec1e2395
