name: local
variables:
  - name: baseUrl
    value: http://localhost:3000/api/v1
  - secret: true
    name: accessToken
  - secret: true
    name: sessionId
  - name: accessTokenExpiry
    value:
      type: number
      data: "1787146647000"
  - name: clientId
    value: e95c0a1e-9f05-411b-90ee-fb9a203241bf
